name: csv_scan
dependencies:
- python=3.5.0=1
# Pandas and its requirements
- numpy=1.10.1=py35_0
- pandas=0.17.0=np110py35_0

# General Python modules
- openssl=1.0.2d=0
- pip=7.1.2=py35_0
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- readline=6.2=2
- setuptools=18.4=py35_0
- six=1.10.0=py35_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- zlib=1.2.8=0


